using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Indtec.ExcelMapper.Generators;

[Generator]
public sealed class ExcelMapperGenerator : IIncrementalGenerator
{
    private const string SheetAttribute = "Indtec.ExcelMapper.ExcelSheetAttribute";
    private const string ColumnAttribute = "Indtec.ExcelMapper.ExcelColumnAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var models = context.SyntaxProvider.ForAttributeWithMetadataName(
            SheetAttribute,
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, _) => CreateModel(ctx));

        context.RegisterSourceOutput(models, static (spc, model) => Emit(spc, model));
    }

    private static ModelInfo CreateModel(GeneratorAttributeSyntaxContext context)
    {
        var type = (INamedTypeSymbol)context.TargetSymbol;
        var sheetName = (string?)context.Attributes[0].ConstructorArguments[0].Value ?? type.Name;
        var isPartial = type.DeclaringSyntaxReferences.Select(x => x.GetSyntax()).OfType<ClassDeclarationSyntax>()
            .Any(x => x.Modifiers.Any(SyntaxKind.PartialKeyword));

        var columns = new List<ColumnInfo>();
        foreach (var property in type.GetMembers().OfType<IPropertySymbol>())
        {
            var attribute = property.GetAttributes().FirstOrDefault(x => x.AttributeClass?.ToDisplayString() == ColumnAttribute);
            if (attribute is null) continue;

            var header = (string?)attribute.ConstructorArguments[0].Value ?? property.Name;
            var order = int.MaxValue;
            var required = false;
            string? converterType = null;

            foreach (var namedArgument in attribute.NamedArguments)
            {
                if (namedArgument.Key == "Order" && namedArgument.Value.Value is int value) order = value;
                if (namedArgument.Key == "Required" && namedArgument.Value.Value is bool requiredValue) required = requiredValue;
                if (namedArgument.Key == "Converter" && namedArgument.Value.Value is INamedTypeSymbol converter)
                    converterType = converter.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            }

            columns.Add(new ColumnInfo(
                property.Name,
                property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                header,
                order,
                property.SetMethod is not null && !property.SetMethod.IsInitOnly,
                required,
                converterType));
        }

        return new ModelInfo(
            type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString(),
            type.Name,
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            sheetName,
            isPartial,
            columns);
    }

    private static void Emit(SourceProductionContext context, ModelInfo model)
    {
        if (!model.IsPartial)
        {
            context.ReportDiagnostic(Diagnostic.Create(new DiagnosticDescriptor(
                "IEM001", "Excel mapped type must be partial",
                "Type '{0}' must be declared partial so Indtec.ExcelMapper can generate its strongly typed map",
                "Indtec.ExcelMapper", DiagnosticSeverity.Error, true), Location.None, model.Name));
            return;
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        if (model.Namespace is not null)
        {
            source.Append("namespace ").Append(model.Namespace).AppendLine();
            source.AppendLine("{");
        }

        source.Append("partial class ").Append(model.Name)
            .AppendLine(" : global::Indtec.ExcelMapper.Mapping.IGeneratedExcelMapProvider");
        source.AppendLine("{");
        source.AppendLine("    private static readonly global::Indtec.ExcelMapper.Mapping.ExcelTypeMap __indtecExcelMap =");
        source.Append("        new global::Indtec.ExcelMapper.Mapping.ExcelTypeMap(")
            .Append(SymbolDisplay.FormatLiteral(model.SheetName, true)).AppendLine(",");
        source.AppendLine("            new global::Indtec.ExcelMapper.Mapping.ExcelColumnMap[]");
        source.AppendLine("            {");

        foreach (var column in model.Columns.OrderBy(x => x.Order).ThenBy(x => x.PropertyName, StringComparer.Ordinal))
        {
            source.Append("                new global::Indtec.ExcelMapper.Mapping.ExcelColumnMap(")
                .Append(SymbolDisplay.FormatLiteral(column.PropertyName, true)).Append(", ")
                .Append(SymbolDisplay.FormatLiteral(column.Header, true)).Append(", ")
                .Append(column.Order).Append(", typeof(").Append(column.TypeName).Append("), ")
                .Append("obj => ((").Append(model.FullyQualifiedName).Append(")obj).@").Append(column.PropertyName).Append(", ");

            if (column.CanWrite)
                source.Append("(obj, value) => ((").Append(model.FullyQualifiedName).Append(")obj).@").Append(column.PropertyName)
                    .Append(" = (").Append(column.TypeName).Append(")value!");
            else
                source.Append("null");

            source.Append(", ").Append(column.Required ? "true" : "false").Append(", ");
            source.Append(column.ConverterType is null ? "null" : "new " + column.ConverterType + "()");
            source.AppendLine("),");
        }

        source.AppendLine("            });");
        source.AppendLine("    global::Indtec.ExcelMapper.Mapping.ExcelTypeMap global::Indtec.ExcelMapper.Mapping.IGeneratedExcelMapProvider.ExcelMap => __indtecExcelMap;");
        source.AppendLine("}");
        if (model.Namespace is not null) source.AppendLine("}");

        context.AddSource(model.Name + ".IndtecExcelMap.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private sealed class ModelInfo
    {
        public ModelInfo(string? @namespace, string name, string fullyQualifiedName, string sheetName, bool isPartial, IReadOnlyList<ColumnInfo> columns)
        { Namespace = @namespace; Name = name; FullyQualifiedName = fullyQualifiedName; SheetName = sheetName; IsPartial = isPartial; Columns = columns; }
        public string? Namespace { get; }
        public string Name { get; }
        public string FullyQualifiedName { get; }
        public string SheetName { get; }
        public bool IsPartial { get; }
        public IReadOnlyList<ColumnInfo> Columns { get; }
    }

    private sealed class ColumnInfo
    {
        public ColumnInfo(string propertyName, string typeName, string header, int order, bool canWrite, bool required, string? converterType)
        { PropertyName = propertyName; TypeName = typeName; Header = header; Order = order; CanWrite = canWrite; Required = required; ConverterType = converterType; }
        public string PropertyName { get; }
        public string TypeName { get; }
        public string Header { get; }
        public int Order { get; }
        public bool CanWrite { get; }
        public bool Required { get; }
        public string? ConverterType { get; }
    }
}
