namespace Indtec.ExcelMapper.Localization;

/// <summary>Languages with built-in mapper-generated messages.</summary>
public enum ExcelLanguage
{
    /// <summary>Uses the built-in English messages.</summary>
    English,

    /// <summary>Uses the built-in Brazilian Portuguese messages.</summary>
    PortugueseBrazil
}

/// <summary>Configures language and mapper-generated messages for an <see cref="ExcelMapper"/> instance.</summary>
public sealed class ExcelMapperOptions
{
    /// <summary>Gets or sets the built-in language. Ignored when <see cref="Messages"/> is provided.</summary>
    public ExcelLanguage Language { get; set; } = ExcelLanguage.English;

    /// <summary>
    /// Gets or sets a custom message provider. Derive from <see cref="ExcelMessageProvider"/>
    /// to override only selected messages, or implement <see cref="IExcelMessageProvider"/> for complete control.
    /// </summary>
    public IExcelMessageProvider? Messages { get; set; }

    internal IExcelMessageProvider ResolveMessages()
        => Messages ?? (Language == ExcelLanguage.PortugueseBrazil
            ? ExcelMessages.PortugueseBrazil
            : ExcelMessages.English);
}

/// <summary>
/// Supplies text for errors and Excel validation prompts generated by the mapper.
/// Application validation messages passed to <c>Validate</c> are not resolved through this provider.
/// </summary>
public interface IExcelMessageProvider
{
    /// <summary>Used when synchronous import is attempted with async batch validators. Default: "Batch validators require ImportAsync because they may perform asynchronous work."</summary>
    string BatchValidatorsRequireAsync();

    /// <summary>Used when a full-sheet batch validator is registered for streaming chunk import. Default: "Batch validators are not supported by streaming chunk imports because they require full-sheet context. Validate inside the chunk callback or use ImportAsync."</summary>
    string StreamingBatchValidatorsNotSupported();

    /// <summary>Used when the mapped worksheet cannot be found. <paramref name="sheetName"/> is the expected worksheet name. Default example: "Worksheet 'Products' was not found."</summary>
    string WorksheetNotFound(string sheetName);

    /// <summary>Used when one or more <c>Required</c> mapped columns are absent. <paramref name="columns"/> contains the canonical missing headers. Default example: "Required columns were not found in worksheet 'Products': Id, Name."</summary>
    string RequiredColumnsNotFound(string sheetName, IReadOnlyList<string> columns);

    /// <summary>Used when import targets a mapped property that cannot be written. <paramref name="header"/> is its canonical Excel header. Default example: "Property mapped to 'Id' is read-only and cannot be imported."</summary>
    string ReadOnlyProperty(string header);

    /// <summary>Used when an empty cell is mapped to a non-nullable value type. Default example: "Cell A2 is empty but 'Int32' is not nullable."</summary>
    string EmptyCellNotNullable(string address, string typeName);

    /// <summary>Used when a cell value cannot be converted to the mapped property type. Default example: "Could not convert cell D3 to 'Decimal'."</summary>
    string CouldNotConvertCell(string address, string typeName);

    /// <summary>Used by streaming import when a cell has no Excel reference such as <c>A2</c>. Default: "A streamed cell is missing its Excel reference."</summary>
    string MissingCellReference();

    /// <summary>Used by streaming import when <paramref name="reference"/> is not a valid Excel cell reference. Default example: "Invalid Excel cell reference '???'."</summary>
    string InvalidCellReference(string reference);

    /// <summary>Used when workbook import is configured without any registered sheets. Default: "At least one sheet must be registered for workbook import."</summary>
    string AtLeastOneSheetForImport();

    /// <summary>Used when workbook export is configured without any registered sheets. Default: "At least one sheet must be registered for workbook export."</summary>
    string AtLeastOneSheetForExport();

    /// <summary>Used when <see cref="Importing.ExcelEmptyRowBehavior.Error"/> encounters an empty row. Default example: "Row 3 is empty."</summary>
    string EmptyRow(int row);

    /// <summary>Used when the same model type is registered more than once for workbook import. Default example: "Model 'Product' was registered more than once in the workbook import."</summary>
    string DuplicateWorkbookModel(string modelName);

    /// <summary>Used when a workbook validator returns an error for a model that was not registered in the import. Default example: "Workbook validator returned an error for unregistered model 'Product'."</summary>
    string UnregisteredWorkbookModel(string modelName);

    /// <summary>Used when workbook template generation is configured without any registered sheets. Default: "At least one sheet must be registered for workbook template generation."</summary>
    string AtLeastOneSheetForTemplate();

    /// <summary>Used when two workbook export/template registrations resolve to the same worksheet name. Default example: "Worksheet 'Products' was registered more than once."</summary>
    string DuplicateWorksheet(string sheetName);

    /// <summary>Used when <c>TemplateRows</c> is zero or negative. Default: "TemplateRows must be greater than zero."</summary>
    string InvalidTemplateRows();

    /// <summary>Used when an inline Excel validation list exceeds Excel's supported length. Default example: "Allowed values for 'Status' exceed Excel's 255-character inline validation limit."</summary>
    string AllowedValuesTooLong(string header);

    /// <summary>Title used by generated Excel data-validation error prompts. Default: "Invalid value".</summary>
    string InvalidValueTitle();

    /// <summary>Message used by generated Excel data-validation error prompts. Default example: "Choose one of the allowed values for Status."</summary>
    string InvalidAllowedValue(string header);
}

/// <summary>Provides the built-in message providers.</summary>
public static class ExcelMessages
{
    /// <summary>Gets the built-in English provider.</summary>
    public static IExcelMessageProvider English { get; } = new EnglishExcelMessageProvider();

    /// <summary>Gets the built-in Brazilian Portuguese provider.</summary>
    public static IExcelMessageProvider PortugueseBrazil { get; } = new PortugueseBrazilExcelMessageProvider();
}

internal sealed class EnglishExcelMessageProvider : IExcelMessageProvider
{
    public string BatchValidatorsRequireAsync() => "Batch validators require ImportAsync because they may perform asynchronous work.";
    public string StreamingBatchValidatorsNotSupported() => "Batch validators are not supported by streaming chunk imports because they require full-sheet context. Validate inside the chunk callback or use ImportAsync.";
    public string WorksheetNotFound(string sheetName) => $"Worksheet '{sheetName}' was not found.";
    public string RequiredColumnsNotFound(string sheetName, IReadOnlyList<string> columns) => $"Required columns were not found in worksheet '{sheetName}': {string.Join(", ", columns)}.";
    public string ReadOnlyProperty(string header) => $"Property mapped to '{header}' is read-only and cannot be imported.";
    public string EmptyCellNotNullable(string address, string typeName) => $"Cell {address} is empty but '{typeName}' is not nullable.";
    public string CouldNotConvertCell(string address, string typeName) => $"Could not convert cell {address} to '{typeName}'.";
    public string MissingCellReference() => "A streamed cell is missing its Excel reference.";
    public string InvalidCellReference(string reference) => $"Invalid Excel cell reference '{reference}'.";
    public string AtLeastOneSheetForImport() => "At least one sheet must be registered for workbook import.";
    public string AtLeastOneSheetForExport() => "At least one sheet must be registered for workbook export.";
    public string EmptyRow(int row) => $"Row {row} is empty.";
    public string DuplicateWorkbookModel(string modelName) => $"Model '{modelName}' was registered more than once in the workbook import.";
    public string UnregisteredWorkbookModel(string modelName) => $"Workbook validator returned an error for unregistered model '{modelName}'.";
    public string AtLeastOneSheetForTemplate() => "At least one sheet must be registered for workbook template generation.";
    public string DuplicateWorksheet(string sheetName) => $"Worksheet '{sheetName}' was registered more than once.";
    public string InvalidTemplateRows() => "TemplateRows must be greater than zero.";
    public string AllowedValuesTooLong(string header) => $"Allowed values for '{header}' exceed Excel's 255-character inline validation limit.";
    public string InvalidValueTitle() => "Invalid value";
    public string InvalidAllowedValue(string header) => $"Choose one of the allowed values for {header}.";
}

internal sealed class PortugueseBrazilExcelMessageProvider : IExcelMessageProvider
{
    public string BatchValidatorsRequireAsync() => "Validadores em lote exigem ImportAsync porque podem executar operações assíncronas.";
    public string StreamingBatchValidatorsNotSupported() => "Validadores em lote não são suportados na importação streaming em chunks porque exigem o contexto completo da planilha. Valide no callback do chunk ou use ImportAsync.";
    public string WorksheetNotFound(string sheetName) => $"A planilha '{sheetName}' não foi encontrada.";
    public string RequiredColumnsNotFound(string sheetName, IReadOnlyList<string> columns) => $"Colunas obrigatórias não foram encontradas na planilha '{sheetName}': {string.Join(", ", columns)}.";
    public string ReadOnlyProperty(string header) => $"A propriedade mapeada para '{header}' é somente leitura e não pode ser importada.";
    public string EmptyCellNotNullable(string address, string typeName) => $"A célula {address} está vazia, mas '{typeName}' não aceita nulo.";
    public string CouldNotConvertCell(string address, string typeName) => $"Não foi possível converter a célula {address} para '{typeName}'.";
    public string MissingCellReference() => "Uma célula lida em streaming não possui referência do Excel.";
    public string InvalidCellReference(string reference) => $"A referência de célula do Excel '{reference}' é inválida.";
    public string AtLeastOneSheetForImport() => "Ao menos uma planilha deve ser registrada para importar o workbook.";
    public string AtLeastOneSheetForExport() => "Ao menos uma planilha deve ser registrada para exportar o workbook.";
    public string EmptyRow(int row) => $"A linha {row} está vazia.";
    public string DuplicateWorkbookModel(string modelName) => $"O modelo '{modelName}' foi registrado mais de uma vez na importação do workbook.";
    public string UnregisteredWorkbookModel(string modelName) => $"O validador do workbook retornou um erro para o modelo não registrado '{modelName}'.";
    public string AtLeastOneSheetForTemplate() => "Ao menos uma planilha deve ser registrada para gerar o template do workbook.";
    public string DuplicateWorksheet(string sheetName) => $"A planilha '{sheetName}' foi registrada mais de uma vez.";
    public string InvalidTemplateRows() => "TemplateRows deve ser maior que zero.";
    public string AllowedValuesTooLong(string header) => $"Os valores permitidos para '{header}' excedem o limite de 255 caracteres da validação inline do Excel.";
    public string InvalidValueTitle() => "Valor inválido";
    public string InvalidAllowedValue(string header) => $"Escolha um dos valores permitidos para {header}.";
}
